# Generated by Django 2.2.6 on 2020-05-02 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("grade", models.DecimalField(decimal_places=1, max_digits=2)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="usuarios.Student")),
            ],
        ),
    ]
