# Generated by Django 2.2.6 on 2020-05-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_auto_20200501_2025"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseperstudent",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="courseperstudent",
            name="grades",
        ),
        migrations.RemoveField(
            model_name="courseperstudent",
            name="students",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="CoursePerStudent",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
    ]
